### ISSUE TITLE
Blazor Auto web app

### ISSUE THREAD

**Issue by 0xmcha** [tesar-tech/BlazorAndTailwind#7]
Hi , why this method doesn’t work with Auto Render mode? Where you get two apps ie (app and app.client)

**Comment by tesar-tech** [comment]
I am not sure method are you talking about..?

If you have two apps in Blazor 8 Web App project you are good with one css file on the server part... Tailwind config needs to "see" also the client.

If that's what you asking about I can provide tailwind.config.js or the structure I have in Blazor 8 Web App proj.

**Comment by 0xmcha** [comment]
> I am not sure method are you talking about..?
> 
> If you have two apps in Blazor 8 Web App project you are good with one css file on the server part... Tailwind config needs to "see" also the client.
> 
> If that's what you asking about I can provide tailwind.config.js or the structure I have in Blazor 8 Web App proj.

Sorry for not being clear, basically i want to use Tailwindcss on Blazor .Net 8 with auto render mode, when i create the project and do the steps on this github, It doesn’t work. it only works on Server render mode.

EDIT: I mean if you can teach me how to add the client side to the tailwind config it would be much appreciated!

**Comment by tesar-tech** [comment]
it depends how is your client configure - what is the relation with the project where you have tw configured. Can you share the project?

There is nothing special with auto render or client project in Blazor.

**Comment by 0xmcha** [comment]
The client is the default when i create a new blazor project Blazorapp.Client and Blazorapp.server.
I probably sound dumb but English isn’t my first language nor its second 😅

**Comment by tesar-tech** [comment]
I need more info about your project. Show me where is the tailwind config, how it looks like, what is the structure of your project and what is the specific error you are facing... etc.

**Comment by 0xmcha** [comment]
![hello-world](https://github.com/tesar-tech/BlazorAndTailwind/assets/110252456/86d585c0-4baa-4cb8-96ee-765572e0e3fc)
![preview](https://github.com/tesar-tech/BlazorAndTailwind/assets/110252456/646448f2-fd09-471d-9a5c-b1e7bdd2d773)
![Projectsetup](https://github.com/tesar-tech/BlazorAndTailwind/assets/110252456/5efc6b61-40cd-40ef-9864-53de63eec258)
![solution](https://github.com/tesar-tech/BlazorAndTailwind/assets/110252456/ef4ab27f-45f1-4c6b-84a9-d87700d8c6c7)
![tailwind-js](https://github.com/tesar-tech/BlazorAndTailwind/assets/110252456/87f47504-b973-4f29-be3a-ec5478c0ab5b)

this is the whole thing , as you can see on my tailwindtest.client project tailwind doesnt work

**Comment by tesar-tech** [comment]
The important thing is, where the home page is located?

If it's located in Client project, you need to also set the content path to there. Since the Client project is next to the TailwindTest, you need to specify something like:

`'../TailwindTest.Client/**/*.razor'` or similar

**Comment by 0xmcha** [comment]
Yeah all the pages are located in Tailwindtest.Client project im splitting the project where client side are Homepage , dashboard, other pages, and back end stuff in the tailwindtest.server project , im gonna try your solution and see if it will work. Much appreciated it 🙏🙏🙏

**Comment by 0xmcha** [comment]
Update: Thank you its working now! , Much appreciated. you're life saver <3

**Comment by tesar-tech** [comment]
Would you mind to make documentation changes to include the solution?

You are probably not the only one with such question and it would be beneficial to have this knowledge included.

**Comment by 0xmcha** [comment]
Hi! Sorry for the late reply i had health problems. sorry but i don't understand what do you mean?. My English language isn’t great 😅.

**Comment by tesar-tech** [comment]
I mean - can you put the knowledge you obtain in this issue into the README.md file?
